
import { MetroStation, CrowdCategory } from './types';

export const STATIONS: MetroStation[] = [
  { id: 'rajiv-chowk', nameEn: 'Rajiv Chowk', nameHi: 'राजीव चौक', line: 'Yellow/Blue' },
  { id: 'kashmere-gate', nameEn: 'Kashmere Gate', nameHi: 'कश्मीरी गेट', line: 'Yellow/Red/Violet' },
  { id: 'hauz-khas', nameEn: 'Hauz Khas', nameHi: 'हौज खास', line: 'Yellow/Magenta' },
  { id: 'noida-city-centre', nameEn: 'Noida City Centre', nameHi: 'नोएडा सिटी सेंटर', line: 'Blue' },
  { id: 'dwarka-sec-21', nameEn: 'Dwarka Sector 21', nameHi: 'द्वारका सेक्टर 21', line: 'Blue/Orange' },
  { id: 'chandni-chowk', nameEn: 'Chandni Chowk', nameHi: 'चांदनी चौक', line: 'Yellow' },
  { id: 'huda-city-centre', nameEn: 'HUDA City Centre', nameHi: 'हुडा सिटी सेंटर', line: 'Yellow' },
];

export const TRANSLATIONS = {
  en: {
    projectName: 'Metro Mitra',
    dashboard: 'Dashboard',
    checkCrowd: 'Check Crowd Status',
    reportCrowd: 'Report Crowd',
    leaderboard: 'Leaderboard',
    insights: 'Insights',
    profile: 'Profile',
    cityCrowdLevel: 'City Crowd Level',
    mostCrowded: 'Most Crowded Stations',
    safestWindows: 'Safest Travel Windows',
    crowdTrends: 'Crowd Trends Today',
    quickSearch: 'Search station...',
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    critical: 'Critical',
    increasing: 'Increasing',
    stable: 'Stable',
    decreasing: 'Decreasing',
    confidence: 'Confidence Score',
    prediction: 'Prediction',
    advice: 'Travel Advice',
    selectStation: 'Select Metro Station',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    analyze: 'Analyze Status',
    authenticity: 'AI Authenticity Check',
    likelyReal: 'Likely Real Image',
    possiblyAI: 'Possibly AI-Generated',
    trustScore: 'Trust Score',
    points: 'Total Points',
    contributions: 'Contributions',
    rank: 'Rank',
    username: 'Username',
    daily: 'Daily',
    weekly: 'Weekly',
    allTime: 'All-time',
    disclaimer: 'Predictions are advisory, not official. AI outputs are probabilistic.',
  },
  hi: {
    projectName: 'मेट्रो मित्र',
    dashboard: 'डैशबोर्ड',
    checkCrowd: 'भीड़ की स्थिति जांचें',
    reportCrowd: 'भीड़ की रिपोर्ट करें',
    leaderboard: 'लीडरबोर्ड',
    insights: 'इनसाइट्स',
    profile: 'प्रोफ़ाइल',
    cityCrowdLevel: 'शहर में भीड़ का स्तर',
    mostCrowded: 'सबसे अधिक भीड़ वाले स्टेशन',
    safestWindows: 'यात्रा के लिए सुरक्षित समय',
    crowdTrends: 'आज भीड़ के रुझान',
    quickSearch: 'स्टेशन खोजें...',
    low: 'कम',
    moderate: 'मध्यम',
    high: 'उच्च',
    critical: 'गंभीर',
    increasing: 'बढ़ रहा है',
    stable: 'स्थिर',
    decreasing: 'घट रहा है',
    confidence: 'आत्मविश्वास स्कोर',
    prediction: 'भविष्यवाणी',
    advice: 'यात्रा सलाह',
    selectStation: 'मेट्रो स्टेशन चुनें',
    selectDate: 'तारीख चुनें',
    selectTime: 'समय चुनें',
    analyze: 'स्थिति का विश्लेषण करें',
    authenticity: 'AI प्रमाणिकता जांच',
    likelyReal: 'संभवतः वास्तविक छवि',
    possiblyAI: 'संभवतः AI-जनित',
    trustScore: 'ट्रस्ट स्कोर',
    points: 'कुल अंक',
    contributions: 'योगदान',
    rank: 'रैंक',
    username: 'यूजरनेम',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
    allTime: 'कुल समय',
    disclaimer: 'भविष्यवाणियां सलाहकार हैं, आधिकारिक नहीं। AI आउटपुट संभाव्यता पर आधारित हैं।',
  }
};

export const CROWD_COLORS = {
  [CrowdCategory.LOW]: 'text-teal-400 bg-teal-400/10',
  [CrowdCategory.MODERATE]: 'text-yellow-400 bg-yellow-400/10',
  [CrowdCategory.HIGH]: 'text-orange-400 bg-orange-400/10',
  [CrowdCategory.CRITICAL]: 'text-red-400 bg-red-400/10',
};
